language: node_js
node_js:
  - 'stable'
  - '4.2'
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - '0.10'
before_script:
  - npm install -g gulp
script:
  - gulp test
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose
